# .travis.xml for use with EPICS Base ci-scripts
# (see: https://github.com/epics-base/ci-scripts)

language: cpp
compiler: gcc
dist: trusty

cache:
  directories:
  - $HOME/.cache

env:
  global:
    - SETUP_PATH=.ci-local:.ci
    - MODULES="asyn calc"
    - ASYN_HOOK=.ci-local/fix_RELEASE.sh
    - CALC_HOOK=.ci-local/fix_RELEASE.sh
    - BASE=R7.0.3
    - TEST=NO

addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - libpcre3-dev
  homebrew:
    packages: re2c

install:
  - .ci/travis/prepare.sh
  - .ci-local/fix_RELEASE.sh

script:
  - .ci/travis/build.sh

matrix:
  include:
  - env: BASE=R3.14.12.8
  - env: BASE=R3.15.6
  - env: BASE=R7.0.3

# Windows
    
  - env: BASE=R3.14.12.8 WINE=32 STATIC=YES
    compiler: mingw

#  - env: BASE=R3.14.12.8 WINE=32 STATIC=NO
#    compiler: mingw

  - env: BASE=R3.14.12.8 WINE=64 STATIC=YES
    compiler: mingw

#  - env: BASE=R3.14.12.8 WINE=64 STATIC=NO
#    compiler: mingw

  - env: BASE=R3.15.6 WINE=32 STATIC=YES
    compiler: mingw

#  - env: BASE=R3.15.6 WINE=32 STATIC=NO
#    compiler: mingw

  - env: BASE=R3.15.6 WINE=64 STATIC=YES
    compiler: mingw

#  - env: BASE=R3.15.6 WINE=64 STATIC=NO
#    compiler: mingw

  - env: BASE=R7.0.3 WINE=32 STATIC=YES
    compiler: mingw

  - env: BASE=R7.0.3 WINE=32 STATIC=NO
    compiler: mingw

  - env: BASE=R7.0.3 WINE=64 STATIC=YES
    compiler: mingw

  - env: BASE=R7.0.3 WINE=64 STATIC=NO
    compiler: mingw

  - env: TEST=NO STATIC=NO
    os: windows
    compiler: cl

# RTEMS

  - env: RTEMS=4.10

  - env: RTEMS=4.9

# MacOS
  - os: osx
    compiler: clang
