# .travis.xml for use with EPICS Base ci-scripts
# (see: https://github.com/epics-base/ci-scripts)

language: cpp
compiler: gcc
dist: xenial

cache:
  directories:
  - $HOME/.cache

env:
  global:
    - SETUP_PATH=.ci-local:.ci
    - MODULES="asyn calc"
    - ASYN_HOOK=.ci-local/fix_RELEASE.sh
    - CALC_HOOK=.ci-local/fix_RELEASE.sh

addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - libpcre3-dev

install:
  - .ci/travis/prepare.sh
  - .ci-local/fix_RELEASE.sh

script:
  - .ci/travis/build.sh

matrix:
  include:
  - env: BASE=R3.14.12.8
  - env: BASE=R3.15.6
  - env: BASE=R7.0.3
